language: python
python:
  - "3.5"
env:
  - FLASK=0.11.1
matrix:
  exclude:
    - python: "3.5"
      env: FLASK=0.9
install:
  - pip install flask==$FLASK coverage
  - pip install -e .
script:
  - python setup.py test
