version: "2"

services:

  web:
    build: ../
    container_name: "web"
    ports:
      - "5001:5000"
    volumes:
      - .:/src
    links:
      - mongo
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: mongo
    volumes:
      - ./data:/data/db
    ports:
      - '27017:27017'
